import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import './globals.css';

import Sidebar from '@/components/sidebar/Sidebar';
import Header from '@/components/header/Header';

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by Krisno Mukti',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${figtree.className} flex`}>
        <Sidebar />

        <main>
          <Header />

          {children}
        </main>
      </body>
    </html>
  );
}
